### ISSUE TITLE
Use @sh?

### ISSUE THREAD

**Issue by nicowilliams** [joelpurra/jqnpm#2]
I see the comments about it.  It turns out there's no simple way to do it, right?

It took some trying, but here's an idiom that works:

    $ unset j
    $ typeset -a j
    $ eval "j=($(./jq -rn '("foo bar","foo\nbar","foo*bar","foo'"'"'bar","foo\"bar") | @sh "\(.)"'))"

So if you're trying to get a list of things, that's how you'd do it.

It'd be nice to be able to take something like a complex object and output `$_<key>__<key>__...="<quoted-value>"` values that can be set in the shell...  Or perhaps a mapping to KSH's "composite" variables (which I've not tried in ages because they never worked well back when I wanted them).

**Comment by nicowilliams** [comment]
Oh, and:

    $ printf 'ONE VALUE: %s\n' "${j[@]}"
    ONE VALUE: foo bar
    ONE VALUE: foo
    bar
    ONE VALUE: foo*bar
    ONE VALUE: foo'bar
    ONE VALUE: foo"bar
    $ 

as expected.

**Comment by joelpurra** [comment]
@nicowilliams: closing, as I think this issue has been superseded by #4.

**Comment by joelpurra** [comment]
(I meant #3.)
